### PR TITLE
Feature message from Queneni

### PR DESCRIPTION
**Pull request by vincib**
this pull request aims at validating the commits from Quenenni

### CODE REVIEW

**Comment by camlafit** [comment]
Hello

I do fast review, I think should be better to continue a deprecated class m_err as m_message wrapper.
Between native code and plugin , looks better to prevent any break. In next major release then we'll delete this old class.

**Comment by quenenni** [comment]
Hello,

I have more time to work on this.

I see that "All checks have failed", but I could'nt find the reason why..
What exactly failed the tests?

@camlafit : you can of course put back the m_error class.

@camlafit : It was necessary to update the create_pass function as it could send back (and did that regularly) wrong results, like passwords with only lower alpha chars. That was quite bad for the users as they generated a password and when they wanted to validate the form, they had an error.

**Comment by quenenni** [comment]
Nice. Thanks.

A question though..
If I want to add more changes / fixes, do I add them to this branch or ..?
Ie:
* I want to cancel what I did for the logo images displayed in the menu,
* I still have a problem with multiple identical msgs when coming back to the interface and the session is not good anymore
* When deleting a domain name, the catchall is not deleted from de DB

It's not blocking problems, so no urgency here.

**Comment by albancrommer** [comment]
Please put them in a new branch, so we can better keep track of what's new / incoming, please :)

**Comment by quenenni** [comment]
Ok. Thanks

**Comment by camlafit** [comment]
Hello

About travis check, don't worry. Our configuration is not complete and actually fail in any case. It's to impove.

About m_error we have find an example in mailman plugin. In this case we have patch the plugin and we'll add a backport m_error to permit old code to continue their work.

About password management looks a new feature , then a new branch to propose.

**Pull request merged**
