### PR TITLE
Fix #230: Rebase to jessie/stretch

### LINKED ISSUE #230: Roll wheezy, jessie, and stretch patches into source tree
It would simplify development to roll the existing patch sets for wheezy, jessie, and stretch into the source tree to build for stable by default.

The default build is for oldoldoldstable... a bit funky. I think that should builds be needed for wheezy/jessie that the patch folders apply reverse patches where necessary.

### PR DESCRIPTION
**Pull request by kienanstewart**
Applied wheezy and jessie patches. Added scripts to revert to squeeze and wheezy if needed.

### CODE REVIEW

**Comment by lelutin** [comment]
This IMHO is a step in the good direction. building packages is currently more complex than it should be: one would presumably build the most recent version more easily than the oldest one.

Apparently unit tests were not written for the jessie version however so there's a missing "m_variables" class when running phpunit. This should be fixed before merging.

But I'm all for seeing this change get in upstream.

Once we have the patching switched around, then it becomes more easy to maintain the latest version on the master branch, and other releases in different branches and use git's branching power to manage patches for us. But incremental changes: first let's make master be the most recent code available!

**Comment by kienanstewart** [comment]
+1 for using branches for the older versions.

i'll see what I can do about the CI tests... looks like the last pass was 4 years ago : https://travis-ci.org/AlternC/AlternC/builds/28306659

**Comment by kienanstewart** [comment]
heh i poked at the tests a bit but given that they haven't been updated really since 2014 and a mostly just un-implemented stubs I don't think it's worth doing here. should be a separate issue

**Comment by lelutin** [comment]
agreed, if fixing tests becomes a big venture, then it should be split into another issue, especially judging from the state the tests are actually in

@vincib what do you think about the original proposition in this PR?

**Comment by vincib** [comment]
This patch is a lot too big to be accepted as one :) 
I'll cherry pick the one we will not merge during devcamp. Thanks !

**Comment by kienanstewart** [comment]
sure thing. the idea was to have the patches already present applied by default, so if that happens, I'm happy :) I'm not worried about keeping patch directories for old versions

**Comment by vincib** [comment]
merged partially with master, cherry picking your commits for those not already patched,
thanks !

**Pull request closed without merging**
