### PR TITLE
allow override of MultiViews option in .htaccess

### PR DESCRIPTION
**Pull request by soul9**
This allows apps to override vhose MultiViews option in .htaccess. I needed this for nextcloud.

### CODE REVIEW

**Comment by camlafit** [comment]
Hello

Can you correct all templates ? 
Looks better to provide only ```Options=Multiviews```  I don't think All options are useful
 
As other example Prestashop  require also multiview override

**Comment by camlafit** [comment]
I'm wrong All is required indeed

**Comment by soul9** [comment]
There. I updated all other vhost templates to allow multiviews as well.

**Comment by camlafit** [comment]
Thanks

**Pull request merged**
